config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Starter Code
  get root to: 'recipes#index'
  resources :recipes
  resources :ingredients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_and_belongs_to_many :recipes, inverse_of: :ingredients
	before_destroy { recipes.clear }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_and_belongs_to_many :ingredients, inverse_of: :recipes
	before_destroy { ingredients.clear }

	def make_new_ingredients(params)
		params[:new_ingredients].split(/\s*,\s*/).each do |ingredient_name|
        @recipe.ingredients.create(name: ingredient_name)
      	end
  	end
end

app/models/recipe_component.rb
class RecipeComponent < ApplicationRecord
  belongs_to :recipe, inverse_of: :recipe_components
  belongs_to :ingredient, inverse_of: :recipe_components
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_url
    else
      redirect_to ingredients_new_url
    end
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredient_url(@ingredient)
    else
      redirect_to ingredients_edit_url
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to ingredients_url
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :is_available)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
     @recipe.make_new_ingredients(params)
      redirect_to recipes_url
    else
      redirect_to recipes_new_url
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
       @recipe.make_new_ingredients(params)
      redirect_to recipe_url(@recipe)
    else
      redirect_to recipes_edit_url
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :made_it_yet, :ingredient_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<h1> Edit Ingredient: <%= @ingredient.name %> </h1>

<%= form_for @ingredient do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :is_available %>
    <%= f.check_box :is_available %>
  </div>
  <%= f.submit "Confirm Edits to Ingredient" %>
<% end %>

<%= link_to 'Cancel', ingredient_path(@ingredient) %>

app/views/ingredients/index.html.erb
<h1> Ingredients </h1>

<ul>
<% @ingredients.each do |ingredient| %>
  <%= link_to ingredient do %>
  <li>
    <p><%= ingredient.name %></p>
  </li>
  <% end %>
<% end %>
</ul>

<%= link_to 'Add a New Ingredient', new_ingredient_path %>

<footer>
  <%= link_to '< Back to recipes', recipes_path %>
</footer>

app/views/ingredients/new.html.erb
<h1> New Ingredient </h1>

<%= form_for @ingredient do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :is_available %>
    <%= f.check_box :is_available %>
  </div>
  <%= f.submit "Create New Ingredient" %>
<% end %>

<% link_to 'Cancel', ingredients_path %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>
<p>
  You <%= @ingredient.is_available ? '' : 'do not' %> have this on hand.
</p>

<%= button_to 'Edit Ingredient', edit_ingredient_path, {method: :get} %>
<%= button_to 'Delete Ingredient', ingredient_path, {method: :delete}%>

<footer>
  <%= link_to '< Back to ingredients list', ingredients_path %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1> Edit Recipe: <%= @recipe.title %> </h1>

<%= form_for @recipe do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :made_it_yet %>
    <%= f.check_box :made_it_yet %>
  </div>
  <%= f.submit "Confirm Edits to Recipe" %> <!-- PATCH to `/recipes/:id` -->

  <div>
  <h4> Ingredients </h4>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
     <p><%= label_tag 'new_ingredients', 'Add New Ingredients Below; Please Separate Names with Commas' %></p>
    <p><%= text_area_tag :new_ingredients %></p>

  </div>
<% end %>

<%= link_to 'Cancel', recipe_path(@recipe) %>

app/views/recipes/index.html.erb
<h1> Recipes </h1>

<ul>
<% @recipes.each do |recipe| %>
  <%= link_to recipe do %>
  <li>
    <p><%= recipe.title %> <%= !recipe.made_it_yet ? '[NEW]' : '' %></p>
  </li>
  <% end %>
<% end %>
</ul>

<%= link_to 'Add a New Recipe', new_recipe_path %>

<footer>
  <%= link_to 'See all ingredients', ingredients_path %>
</footer>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>

<%= form_for @recipe do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :made_it_yet %>
    <%= f.check_box :made_it_yet %>
  </div>

  <div>
    <h4> Ingredients </h4>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
      <p><%= label_tag 'new_ingredients', 'Add New Ingredients Below; Please Separate Names with Commas' %></p>
      <p><%= text_area_tag :new_ingredients %></p>
  </div>  
  
  <%= f.submit "New Recipe" %> <!-- POST to `/recipes` -->
<% end %>

<%= link_to 'Cancel', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p><%= @recipe.description %></p>
<p>
  You have <%= @recipe.made_it_yet ? "already" : "not yet" %> tried out this recipe.
</p>

<ul>
  <lh> Ingredients: </lh>
  <% @recipe.ingredients.each do |ingredient| %>
	  <%= link_to ingredient do %>
	    <li class="<%= ingredient.is_available ? 'available' : 'not-available'%>">
	      <p> <%= ingredient.name %> </p>
	    </li>
	  <% end %>
  <% end %>
</ul>

<%= button_to 'Edit Recipe', edit_recipe_path, {method: :get} %>
<%= button_to 'Delete Recipe', recipe_path, {method: :delete}%>

<footer>
  <%= link_to '< Back to Recipes', recipes_path %>
</footer>